### ISSUE TITLE
adding option for skipping init-script

### ISSUE THREAD

**Issue by sunggun-yu** [sunggun-yu/envp#140]
I have gcp profiles that inits gcloud auth login to ensure the auth before running the gcloud on the project. but I want to skip the init-script for auth when I open another gcp profile since I've done `gcloud auth` already. so that, I can save start time of profile.

```yaml
profiles:
    my-gcp-1:
      desc: my-gcp-1 GCP project
      env:
      - name: PROJECT_ID
        value: my-project-1
      - name: REGION
        value: us-east4
      init-script:
      - run: gcloud auth login
    my-gcp-2:
      desc: my-gcp-1 GCP project
      env:
      - name: PROJECT_ID
        value: my-project-2
      - name: REGION
        value: us-west2
      init-script:
      - run: gcloud auth login
```

current:

```bash
envp start my-gcp-1
// gcloud auth login may opens web browser to login

envp start my-gcp-2
// gcloud auth login may opens web browser again
```

I want to:

```bash
envp start my-gcp-1
// gcloud auth login may opens web browser to login

envp start my-gcp-2 --skip-init
// gcloud auth login won't be executed and it is ok since login is already done
```
