### ISSUE TITLE
leverage the nested profile structure to inherit the env-vars from parent to children.

### ISSUE THREAD

**Issue by sunggun-yu** [sunggun-yu/envp#6]
let's say I have config like this, and `NO_PROXY` is repeating in all profile with same value.

```yaml
profiles:
  gke:
    dev:
      desc: GKE proxy for dev cluster
      env:
      - name: HTTPS_PROXY
        value: http://<ip-addr-dev>:443
      - name: NO_PROXY
        value: localhost,127.0.0.1,.googleapis.com
      - name: KUBECONFIG
        value: /Users/meow/.kube/gke-dev
    qa:
      desc: GKE proxy for qa cluster
      env:
      - name: HTTPS_PROXY
        value: http://<ip-addr-qa>:443
      - name: NO_PROXY
        value: localhost,127.0.0.1,.googleapis.com
      - name: KUBECONFIG
        value: /Users/meow/.kube/gke-qa
    test:
      desc: GKE proxy for test cluster
      env:
      - name: HTTPS_PROXY
        value: http://<ip-addr-test>:443
      - name: NO_PROXY
        value: localhost,127.0.0.1,.googleapis.com
      - name: KUBECONFIG
        value: /Users/meow/.kube/gke-test
```

since parent profile can have `desc` and `env`, set common and repeating env in parent and inherits to the children would be nice.

```yaml
profiles:
  gke:
    desc: GKE proxy group
    env:
    - name: NO_PROXY
      value: localhost,127.0.0.1,.googleapis.com
    dev:
      desc: GKE proxy for dev cluster
      env:
      - name: HTTPS_PROXY
        value: http://<ip-addr-dev>:443
      - name: KUBECONFIG
        value: /Users/meow/.kube/gke-dev
    qa:
      desc: GKE proxy for qa cluster
      env:
      - name: HTTPS_PROXY
        value: http://<ip-addr-qa>:443
      - name: KUBECONFIG
        value: /Users/meow/.kube/gke-qa
    test:
      desc: GKE proxy for test cluster
      env:
      - name: HTTPS_PROXY
        value: http://<ip-addr-test>:443
      - name: KUBECONFIG
        value: /Users/meow/.kube/gke-test
```

**Comment by sunggun-yu** [comment]
use yaml anchor instead 

```yaml
commons: 
  gke:
    no-proxy: &commons-gke-no-proxy
      name: NO_PROXY
      value: localhost,127.0.0.1,.googleapis.com,.amazonaws.com
    gcloud-config-init: &commons-gcloud-config-init |
      # Check if gcloud is already authenticated
      if gcloud auth list | grep -q 'ACTIVE'; then
          echo "Already authenticated."
      else
          echo "Not authenticated. Initiating login..."
          gcloud auth login
      fi
profiles:
  gke:
    my-dev-1:
      desc: GKE proxy for my-dev-1 cluster
      env:
      - <<: *commons-gke-no-proxy
      init-script: *commons-gcloud-config-init
    my-dev-2:
      desc: GKE proxy for my-dev-2 cluster
      env:
      - <<: *commons-gke-no-proxy
      init-script: *commons-gcloud-config-init
```
